### PR TITLE
updated leetcode quetsions and answers

### PR DESCRIPTION
**Pull request by yudataguy**
Now we have a complete json object with all the leetcode question info, which will make things easier for query information, instead of having them in different files. 

this step is also in preparation of the debug agent

### CODE REVIEW

**Comment by yudataguy** [comment]
ignore the test_cases, these will be replaced soon

**Review by minki-j — COMMENTED** [review]
@yudataguy Thanks for the PR. 

Is there a reason to keep every question to one file? I intentionally put them separately because it makes me easy to check each questions.

You said it makes it easier for query information. Why?

_`opening up all files in directory leetcode/scrapped_data` vs `opening up a single file`_


I don't think the latter is significantly better. I'd prefer to keep questions separately. Let me know what you think.

**Comment by yudataguy** [comment]
Which is more efficient? Tracking 1 file vs 1000 files.

1) With the question number, you can retrieve the correct data in O(1) or O(n) depends on how you structure it
2) With each question, the filename is different, without additional database(file), you must have a method to retrieve the right filename, and you must account for special character in title, therefore filenames. It may not be difficult if you only have 10s of files. Think if you have to scale up to hundreds if not thousands of files.

**Comment by minki-j** [comment]
Okay... Can you test the app working fine with your new file? You need to make changes all the parts of the application that uses that data.

**Comment by yudataguy** [comment]
I'll make changes and add new endpoints to process the data

**Comment by yudataguy** [comment]
updated endpoints, now you can easily retrieve entire questions list 
`get_interview_questions`
and
`get_interview_quetsion/{id}`

see readme for detail

**Pull request merged**
